# Generated by Django 2.1.5 on 2019-01-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20190112_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='inout',
            field=models.CharField(max_length=50),
        ),
    ]
