# Generated by Django 2.1.5 on 2019-01-12 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20190112_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.User')),
            ],
        ),
    ]
